#' @name rdbes_sl
#' @title Table Species List (SL) details generation (RDBES process)
#' @description Process for generation and optionally extraction of the RDBES table SL (Species List details).
#' @param rdbes_table_cl {\link[base]{data.frame}} or {\link[tibble]{tibble}} expected. By default NULL. Table CL generated by the function {\link[acdc]{rdbes_cl}}.
#' @param export_path {\link[base]{character}} expected. By default NULL. Directory path associated for the export.
#' @details
#' If the argument "rdbes_table_cl" is provided, the process generates a table SL according to input data of the data.frame/tibble associated (not from a database SQL extraction).
#' @return A R object with the RDBES table SL with potentially a csv extraction associated.
#' @export
#' @importFrom codama r_type_checking
#' @importFrom dplyr select distinct rename mutate case_when
#' @importFrom utils write.csv
rdbes_sl <- function(rdbes_table_cl = NULL,
                     export_path = NULL) {
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start process on RDBES table SL generation.",
          sep = "")
  # 1 - Global variables assignement ----
  CLcatchCat <- NULL
  CLspecCode <- NULL
  CLyear <- NULL
  SLcatchFrac <- NULL
  SLcommTaxon <- NULL
  SLcou <- NULL
  SLinst <- NULL
  SLrecType <- NULL
  SLspeclistName <- NULL
  SLsppCode <- NULL
  SLyear <- NULL
  # 2 - Arguments verifications ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start arguments verifications.",
          sep = "")
  if ((! is.null(x = rdbes_table_cl))
      && codama::r_type_checking(r_object = rdbes_table_cl,
                                 type = "data.frame",
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = rdbes_table_cl,
                                   type = "data.frame",
                                   output = "message"))
  }
  if ((! is.null(x = export_path))
      && codama::r_type_checking(r_object = export_path,
                                 type = "character",
                                 length = 1L,
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = export_path,
                                   type = "character",
                                   length = 1L,
                                   output = "message"))
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful arguments verifications.",
          sep = "")
  # 3 - Databases extractions ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start databases extractions.",
          sep = "")
  #to do in the future
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful databases extractions.",
          sep = "")
  # 4 - Other data extractions ---
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start other data extractions.",
          sep = "")
  # maybe in the future
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful other data extractions.",
          sep = "")
  # 5 - Data design ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start data design.",
          sep = "")
  if (! is.null(x = rdbes_table_cl)) {
    table_sl <- dplyr::select(.data = rdbes_table_cl,
                              CLyear,
                              CLcatchCat,
                              CLspecCode) %>%
      dplyr::distinct() %>%
      dplyr::rename(SLyear = CLyear,
                    SLsppCode = CLspecCode) %>%
      dplyr::mutate(SLrecType = "SL",
                    SLcou = "FR",
                    SLinst = "1836",
                    SLspeclistName = "ird_test_data_call_2023",
                    SLcatchFrac = dplyr::case_when(
                      CLcatchCat == "Lan" ~ "Lan",
                      CLcatchCat == "RegDis" ~ "Dis",
                      TRUE ~ "catch_fraction_missing"
                    ),
                    SLcommTaxon = SLsppCode) %>%
      dplyr::select(SLrecType,
                    SLcou,
                    SLinst,
                    SLspeclistName,
                    SLyear,
                    SLcatchFrac,
                    SLcommTaxon,
                    SLsppCode)
  } else {
    stop(format(x = Sys.time(),
                format = "%Y-%m-%d %H:%M:%S"),
         " - Process not developed yet for sql query table generation",
         sep = "")
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful data design.",
          sep = "")
  # 6 - Extraction ----
  if (! is.null(x = export_path)) {
    message(format(x = Sys.time(),
                   format = "%Y-%m-%d %H:%M:%S"),
            " - Start SL data extractions.",
            sep = "")
    utils::write.csv(x = table_sl,
                     file = file.path(export_path,
                                      paste(format(as.POSIXct(Sys.time()),
                                                   "%Y%m%d_%H%M%S"),
                                            "rdbes_sl.csv",
                                            sep = "_")),
                     row.names = FALSE,
                     na = "")
    message(format(x = Sys.time(),
                   format = "%Y-%m-%d %H:%M:%S"),
            " - Successful SL data extractions.\n",
            "File available in the directory ",
            export_path,
            sep = "")
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful process on RDBES table SL generation.",
          sep = "")
  return(table_sl)
}
