#' @name rdbes_vd
#' @title Table Vessel Details (VD) generation (RDBES process)
#' @description Process for generation and optionally extraction of the RDBES table VD (Vessel Details).
#' @param observe_con {\link[base]{list}} expected. Output of the function {\link[furdeb]{postgresql_dbconnection}} for a connection to the observe database.
#' @param rdbes_table_cl {\link[base]{data.frame}} or {\link[tibble]{tibble}} expected. By default NULL. Table CL generated by the function {\link[acdc]{rdbes_cl}}. Warning encrypted vessel code should be according to the database extraction (especially if there was hashing).
#' @param rdbes_table_ce {\link[base]{data.frame}} or {\link[tibble]{tibble}} expected. By default NULL. Table CE generated by the function {\link[acdc]{rdbes_ce}}. Warning encrypted vessel code should be according to the database extraction (especially if there was hashing).
#' @param flag {\link[base]{integer}} expected. Flag(s) selected associated to the databases queries extractions.
#' @param hash_algorithms {\link[base]{integer}} expected. By default NULL. The hashing algorithms to be used for the VDencrypVesIds variable. You can choose any modality of the argument "algo" or the function {\link[digest]{digest}}.
#' @param encrypted_vessel_code_separator {\link[base]{character}} expected. By default ", ". Which separator you want to use for the VDencrypVesIds variable.
#' @param export_path {\link[base]{character}} expected. By default NULL. Directory path associated for the export.
#' @details
#' If the arguments "rdbes_table_cl", "rdbes_table_ce" or both are provided, the process generates a table VD according to input data of the data.frame/tibble associated (not from a database SQL extraction).
#' @return A R object with the RDBES table VD with potentially a csv extraction associated.
#' @export
#' @importFrom codama r_type_checking
#' @importFrom DBI sqlInterpolate SQL dbGetQuery
#' @importFrom stringr str_split
#' @importFrom dplyr tibble select filter rename left_join distinct case_when inner_join
#' @importFrom utils write.csv
#' @importFrom digest digest
rdbes_vd <- function(observe_con,
                     rdbes_table_cl = NULL,
                     rdbes_table_ce = NULL,
                     flag,
                     hash_algorithms = NULL,
                     encrypted_vessel_code_separator = ", ",
                     export_path = NULL) {
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start process on RDBES table VD generation.",
          sep = "")
  # 1 - Global variables assignement ----
  CEencrypVesIds <- NULL
  CEyear <- NULL
  CLencrypVesIds <- NULL
  CLyear <- NULL
  VDctry <- NULL
  VDencrVessCode <- NULL
  VDflgCtry <- NULL
  VDhomePort <- NULL
  VDlen <- NULL
  VDlenCat <- NULL
  VDpwr <- NULL
  VDrecType <- NULL
  VDton <- NULL
  VDtonUnit <- NULL
  VDyear <- NULL
  alpha_2_code <- NULL
  capacity_m3 <- NULL
  engine_power_cv <- NULL
  vessel_flag_country_fao <- NULL
  VDencrVessCode_hash <- NULL
  # 2 - Arguments verifications ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start arguments verifications.",
          sep = "")
  if (codama::r_type_checking(r_object = observe_con,
                              type = "list",
                              length = 2L,
                              output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = observe_con,
                                   type = "list",
                                   length = 2L,
                                   output = "message"))
  }
  if ((! is.null(x = rdbes_table_cl))
      && codama::r_type_checking(r_object = rdbes_table_cl,
                                 type = "data.frame",
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = rdbes_table_cl,
                                   type = "data.frame",
                                   output = "message"))
  }
  if ((! is.null(x = rdbes_table_ce))
      && codama::r_type_checking(r_object = rdbes_table_ce,
                                 type = "data.frame",
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = rdbes_table_ce,
                                   type = "data.frame",
                                   output = "message"))
  }
  if (codama::r_type_checking(r_object = flag,
                              type = "integer",
                              output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = flag,
                                   type = "integer",
                                   output = "message"))
  }
  if ((! is.null(x = hash_algorithms))
      && codama::r_type_checking(r_object = hash_algorithms,
                                 type = "character",
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = hash_algorithms,
                                   type = "character",
                                   output = "message"))
  }
  if ((! is.null(x = export_path))
      && codama::r_type_checking(r_object = export_path,
                                 type = "character",
                                 length = 1L,
                                 output = "logical") != TRUE) {
    return(codama::r_type_checking(r_object = export_path,
                                   type = "character",
                                   length = 1L,
                                   output = "message"))
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful arguments verifications.",
          sep = "")
  # 3 - Databases extractions ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start databases extractions.",
          sep = "")
  observe_vd_data_query <- paste(readLines(con = system.file("sql",
                                                             "rdbes",
                                                             "observe_vd_rdbes.sql",
                                                             package = "acdc")),
                                 collapse = "\n")
  observe_vd_data_query <- DBI::sqlInterpolate(conn = observe_con[[2]],
                                               sql = observe_vd_data_query,
                                               flag = DBI::SQL(paste0("'",
                                                                      paste0(flag,
                                                                             collapse = "', '"),
                                                                      "'")))
  observe_vd_data <- DBI::dbGetQuery(conn = observe_con[[2]],
                                     statement = observe_vd_data_query)
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful databases extractions.",
          sep = "")
  # 4 - Other data extractions ---
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start other data extractions.",
          sep = "")
  referential_iso_3166 <- read.csv2(file = system.file("referentials",
                                                       "iso_3166.csv",
                                                       package = "acdc"))
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful other data extractions.",
          sep = "")
  # 5 - Data design ----
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Start data design.",
          sep = "")
  if (! is.null(x = rdbes_table_cl)
      | ! is.null(x = rdbes_table_ce)) {
    table_vd <- dplyr::tibble()
    if (! is.null(x = rdbes_table_cl)) {
      table_cl_vessel <- dplyr::select(.data = rdbes_table_cl,
                                       CLencrypVesIds,
                                       CLyear)
      table_cl_vessel_final <- dplyr::tibble()
      for (year in unique(table_cl_vessel$CLyear)) {
        table_cl_vessel_subset <- dplyr::filter(.data = table_cl_vessel,
                                                CLyear == year)
        table_cl_vessel_final <- rbind(table_cl_vessel_final,
                                       dplyr::tibble("CLencrypVesIds" = unique(x = unlist(x = stringr::str_split(string = table_cl_vessel_subset$CLencrypVesIds,
                                                                                                                 pattern = !!encrypted_vessel_code_separator))),
                                                     "CLyear" = year))
      }
      table_vd <- rbind(table_vd,
                        dplyr::rename(.data = table_cl_vessel_final,
                                      VDencrVessCode = CLencrypVesIds,
                                      VDyear = CLyear))
    }
    if (! is.null(x = rdbes_table_ce)) {
      table_ce_vessel <- dplyr::select(.data = rdbes_table_ce,
                                       CEencrypVesIds,
                                       CEyear)
      table_ce_vessel_final <- dplyr::tibble()
      for (year in unique(table_ce_vessel$CEyear)) {
        table_ce_vessel_subset <- dplyr::filter(.data = table_ce_vessel,
                                                CEyear == year)
        table_ce_vessel_final <- rbind(table_ce_vessel_final,
                                       dplyr::tibble("CEencrypVesIds" = unique(x = unlist(x = stringr::str_split(string = table_ce_vessel_subset$CEencrypVesIds,
                                                                                                                 pattern = !!encrypted_vessel_code_separator))),
                                                     "CEyear" = year))
      }
      table_vd <- rbind(table_vd,
                        dplyr::rename(.data = table_ce_vessel_final,
                                      VDencrVessCode = CEencrypVesIds,
                                      VDyear = CEyear))
    }
    if (! is.null(x = hash_algorithms)) {
      observe_vd_data <- dplyr::inner_join(x = observe_vd_data,
                                           y = dplyr::tibble("VDencrVessCode" = unique(x = observe_vd_data$VDencrVessCode)) %>%
                                             dplyr::rowwise() %>%
                                             dplyr::mutate(VDencrVessCode_hash = digest::digest(VDencrVessCode,
                                                                                                algo = !!hash_algorithms)),
                                           by = "VDencrVessCode") %>%
        dplyr::select(-VDencrVessCode) %>%
        dplyr::rename(VDencrVessCode = VDencrVessCode_hash)
    }
    table_vd_final <- dplyr::distinct(.data = table_vd) %>%
      dplyr::left_join(dplyr::select(.data = observe_vd_data,
                                     VDencrVessCode,
                                     vessel_flag_country_fao,
                                     VDlen,
                                     engine_power_cv,
                                     capacity_m3),
                       by = "VDencrVessCode") %>%
      dplyr::left_join(referential_iso_3166[, c("alpha_3_code",
                                                "alpha_2_code")],
                       by = c("vessel_flag_country_fao" = "alpha_3_code")) %>%
      dplyr::rename(VDflgCtry = alpha_2_code) %>%
      dplyr::mutate(VDrecType = "VD",
                    VDctry = "FR",
                    VDhomePort = NA_character_,
                    VDlen = round(x = VDlen,
                                  digits = 2),
                    VDlenCat = dplyr::case_when(
                      VDlen < 6 ~ "VL0006",
                      VDlen >= 6 & VDlen < 8 ~ "VL0608",
                      VDlen >= 8 & VDlen < 10 ~ "VL0810",
                      VDlen >= 10 & VDlen < 12 ~ "VL1012",
                      VDlen >= 12 & VDlen < 15 ~ "VL0608",
                      VDlen >= 15 & VDlen < 18 ~ "VL1518",
                      VDlen >= 18 & VDlen < 24 ~ "VL0608",
                      VDlen >= 24 & VDlen < 40 ~ "VL2440",
                      VDlen >= 40 ~ "VL40XX",
                      TRUE ~ "NK"
                    ),
                    VDpwr = round(x = engine_power_cv * 0.73539875),
                    VDton = round(x = (0.2 + 0.02 * log10(capacity_m3)) * capacity_m3),
                    VDtonUnit = "GT") %>%
      dplyr::select(VDrecType,
                    VDencrVessCode,
                    VDyear,
                    VDctry,
                    VDhomePort,
                    VDflgCtry,
                    VDlen,
                    VDlenCat,
                    VDpwr,
                    VDton,
                    VDtonUnit)
  } else {
    stop(format(x = Sys.time(),
                format = "%Y-%m-%d %H:%M:%S"),
         " - Process not developed yet for sql query table generation",
         sep = "")
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful data design.",
          sep = "")
  # 6 - Extraction ----
  if (! is.null(x = export_path)) {
    message(format(x = Sys.time(),
                   format = "%Y-%m-%d %H:%M:%S"),
            " - Start VD data extractions.",
            sep = "")
    utils::write.csv(x = table_vd_final,
                     file = file.path(export_path,
                                      paste(format(as.POSIXct(Sys.time()),
                                                   "%Y%m%d_%H%M%S"),
                                            "rdbes_vd.csv",
                                            sep = "_")),
                     row.names = FALSE,
                     na = "")
    message(format(x = Sys.time(),
                   format = "%Y-%m-%d %H:%M:%S"),
            " - Successful VD data extractions.\n",
            "File available in the directory ",
            export_path,
            sep = "")
  }
  message(format(x = Sys.time(),
                 format = "%Y-%m-%d %H:%M:%S"),
          " - Successful process on RDBES table VD generation.",
          sep = "")
  return(table_vd_final)
}
